"""remove adress, nicks null again

Revision ID: 042bbc4b6f7d
Revises: 4ec5e087ec9e
Create Date: 2026-08-19 13:46:54.417653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042bbc4b6f7d'
down_revision: Union[str, Sequence[str], None] = '4ec5e087ec9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
