"""tg_link is mandatory

Revision ID: 33aa93d68ad7
Revises: 042bbc4b6f7d
Create Date: 2026-08-19 13:50:22.657710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33aa93d68ad7'
down_revision: Union[str, Sequence[str], None] = '042bbc4b6f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
