"""ad astra

Revision ID: 42f4d5292015
Revises: 33aa93d68ad7
Create Date: 2026-08-19 14:29:21.637527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f4d5292015'
down_revision: Union[str, Sequence[str], None] = '33aa93d68ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slogan', sa.String(), server_default='Per stradania to Sterne', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'slogan')
    # ### end Alembic commands ###
